### ISSUE TITLE
The verdict is consistent false

### ISSUE THREAD

**Issue by fish0607** [JamesSingleton/is-organization-member#13]
Whether the user belongs to the organization or not, return false

**Comment by fidencio** [comment]
@JamesSingleton, I am hitting a similar issue as @fish0607's reported one.

If I do the check like https://github.com/fidencio/kata-containers/blob/686a05391e63821f7dc70d11ddf301720919f533/.github/workflows/kata-deploy-test.yaml#L24-L25, the action will always fail.  If I do the check like suggested in the example here (without `${{ }}`), the action will never fail.

Did this work at some point?  Is this just a regression?

**Comment by JamesSingleton** [comment]
@fish0607 and @fidencio sorry for the delay on this. Can you try `1.0.1` now?

**Comment by fidencio** [comment]
@JamesSingleton, same issue, still:
https://github.com/fidencio/kata-containers/runs/4321142145?check_suite_focus=true

**Comment by JamesSingleton** [comment]
> @JamesSingleton, same issue, still:
> 
> https://github.com/fidencio/kata-containers/runs/4321142145?check_suite_focus=true

Weird because the GitHub workflow in this repo that runs it is posing as expected.

**Comment by fidencio** [comment]
@JamesSingleton, so this is the result I'm getting: https://github.com/fidencio/kata-containers/runs/4328159981?check_suite_focus=true

And this is the code I'm using: https://github.com/fidencio/kata-containers/blob/215c0183a3ed2a99c011f94bf29c062772845356/.github/workflows/kata-deploy-test.yaml#L16-L41

Sorry for bothering, but do you see something that's obviously wrong there?  I am going back and forth with this for some time, and I couldn't spot what may be something obvious for the creator / maintainer.

**Comment by JamesSingleton** [comment]
I wonder if it's the quotes causing issues on the org for some reason. I noticed in my test my org and username don't have quotes but yours do. If that's not the case, I'll have to take a look next week as I'm on vacation at the moment.

**Comment by fidencio** [comment]
> I wonder if it's the quotes causing issues on the org for some reason. I noticed in my test my org and username don't have quotes but yours do. If that's not the case, I'll have to take a look next week as I'm on vacation at the moment.

I appreciate the help.  That's not the case, though, the quotes were added as a desperate try to get it working.  I have runs without that and I get exactly the very same results.

I'll try forking this repo and making it work from here, and we can sync up next week.
Enjoy your time off, happy thanks giving!

**Comment by fidencio** [comment]
Okay, I figured this out and this is on me (or on the user, in general).  Basically, by default members of the org are added with their profile being **Private**, which will cause the action to return `false`, as expected.

Going to my work and changing myself to **Public** solves the "issue".
I think this is serious material for the README, which I can't contribute right now, but I'll soon.

Again, enjoy your holidays!

**Comment by JamesSingleton** [comment]
@fidencio  awesome! I'm glad to hear! If you get a chance to add it before I do, that would be great! ☺️

**Comment by acieroid** [comment]
Sorry to come back to this issue, but even with organization visibility as "public", it seems I consistently get false from this action.
See example of failed check here: https://github.com/AwesomBoard/AwesomBoard/runs/4453491505?check_suite_focus=true:

The job "Check if push by an org member" is defined as:

```
      - name: Check if push by an org member
        id: is_organization_member
        uses: jamessingleton/is-organization-member@1.0.1
        with:
          organization: AwesomBoard
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
``` 
and it produces the following output: 
```
Run jamessingleton/is-organization-member@1.0.1
  with:
    organization: AwesomBoard
    username: acieroid
    token: ***
STARTED
```
and the subsequent job is defined as follows, but *never* gets executed.
```
      - name: Build
        if: steps.is_organization_member.outputs.result == true
        run: npm run build:netlify
```

Note that I am indeed part of the organization, and this is accessible publicly.
I also had to use `github.actor` to access the username instead of `github.event.issue.user.login` as listed in the README.

**Comment by fidencio** [comment]
@acieroid, for some reason I never got the `if` statement to work as expected and I worked this around with https://github.com/kata-containers/kata-containers/blob/7522109abc96cb6bf8247d931ed53eee5e0959d8/.github/workflows/kata-deploy-test.yaml#L25-L35

Let me know if that works for you.

**Comment by acieroid** [comment]
Indeed it works with the same workaround, thanks for the help! Maybe something to mention in the README too :)

**Comment by JamesSingleton** [comment]
@acieroid or @fidencio feel free to open a PR 👍🏼 I honestly had no idea people were using this action 😅
