### ISSUE TITLE
Resolve Github Action deprecations

### ISSUE THREAD

**Issue by bendnorman** [JamesSingleton/is-organization-member#25]
Github wants all actions running on [Node 16 by the summer](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) and is planning on [deprecating `save-state` and `set-output` commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). `is-organization-member` is currently raising these deprecation warnings:

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: JamesSingleton/is-organization-member@1.0.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by JamesSingleton** [comment]
Updated this to Node 20 and some of the dependencies as well

**Comment by Madoshakalaka** [comment]
can we have a release? the last release was 3.5 years ago

**Comment by JamesSingleton** [comment]
I apologize for that... I didn't even really think this action was being used. I just created a 1.1.0
